project_id = "pcxvnqsoafagnthazoir"

[functions.paypal-ipn]
verify_jwt = false

[functions.check-license]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false

[functions.ai-financial-chat]
verify_jwt = false

[functions.market-data]
verify_jwt = false
